---
title: "Explore and Summarize Data"
output: html_notebook
---

## 一、学习背景

### （一）项目概述
在此项目中，将使用 R 并运用探索性数据分析来**探索一个变量或多个变量**之间的关系，以及在一个选定的数据集中**探索分布、异常值和反常现象**。

### （二）我需要安装什么？
install.packages("ggplot2", dependencies = T) 
install.packages("knitr", dependencies = T)
install.packages("dplyr", dependencies = T)

### （三）为什么进行这个项目？
探索性数据分析（EDA）是在应用正式的、严格的统计分析之前，对**数据的特征和关系的进行数字的和图表的测试**。

EDA可以引起人们的洞察力，可以反映其他问题，并最终形成预测模型。
这是对不良数据的一个重要的“防线”，也是一个可以注意到你对数据集的假设或直觉是否正确的机会。

### （三）我会学到什么？
- 了解变量的**分布并检查异常和异常值**
- 通过使用适当的图表如散点图、直方图、条形图和箱图学会**量化和可视化数据集的各个变量**
- 在构建预测模型之前，探究变量来**辨别数据集中最重要的变量和关系，计算他们的相关性，并调查条件均值**
- 学习有用的方法和可视化手段来检查多个变量之间的关系，例如**重新构造数据框架和使用通过颜色和形状来发现更多信息**

### （四）为什么要学习数据分析？
为什么要学习数据分析？如果你想找一个拥有大量需求的职业，你需要为一些越来越常见以及廉价的东西提供稀缺且附带额外价值的服务。那么，什么东西正变得越来越常见和廉价？数据。那么，什么是为数据提供稀缺且附带额外价值的服务？分析。
— Hal Varian, 加州大学伯克利分校，Google 首席经济学家

## 二、项目详情

### 简介
自行完成探索性数据分析，并且创建一个**RMD文件**，以探索选择的**数据集的变量、结构、模式、异常现象和潜在关系**。

从提出问题、创建可视化并且探索数据，深刻了解整个分析过程。

此项目是开放式的，正确答案不止一个。
正如John Tukey 所说：“某些数据和对答案的极度渴望组合起来并不能保证可以从一组给定的数据中获得合理的答案。”

我们希望你提出有趣的数据问题，并且给自己一个探索的机会。我们将提供一些数据集供你探索，但你也可以选择一个完全不同的数据集。
需要注意的是，找出自己的数据集，然后将它整理为 R 可以读取的形式是费时费力的。
你可能要多花一天、一周甚至是几个月的时间才能完成你的项目。
因此，仅在你确实具备编程和数据整理技能时才找出并整理数据集。

现在，让我们来看看项目细节！

### （一）第一步 - 选择数据集
首先，你需要**从数据集选项文档中选择一个数据集**。
你应根据以前的编程和数据处理经验来选择数据集。
你选择的数据集不会增加或减小你通过最终项目考核的几率。
通常，整洁的数据集更容易使用，因为每个变量就是一列，每行就是一个观测值，而且无需整理数据。
我们在下方提供的指导能帮助你选择数据集。
估算的时间包含了阅读所有项目说明和评估准则、进行分析和提交最终项目的时间。

我的选择：红葡萄酒质量。
这个整齐的数据集包含1,599 种红酒，以及 11 个关于酒的化学成分的变量。
至少3名葡萄酒专家对每种酒的质量进行了评分，分数在 0（非常差）和10（非常好）之间。

### （二）第二步 - 确保项目的条理性
你最终会提交项目，并且与你的朋友、家人和雇主分享项目。
在开始之前请确保项目的条理性。
我们建议你在桌面上创建一个单独的文件夹，该文件夹最终将包含：
 1. RMD 文件，它包含**分析报告、最终图形和摘要**，以及依次写下的反思
 2. HTML 文件（通过你的 RMD 文件拼合而成）

### （三）第三步 - 探索数据
这部分很有趣，开始探索你的数据吧！
在探索数据时，将你的想法记录在 RMD 文件中。
请参考我们提供的示例项目。你的报告应类似此项目！

### （四）第四步 - 记录你的分析
在你提交的 RMD 文件中记录探索和分析工作。
该文件应以 markdown 的形式进行格式化，并应依次包含：
#### 1. 以**意识流方式**对数据进行的分析和探索。
  a. 应通过标题和文本组织你的想法，以及反映你在探索数据时的分析工作。
  b. 该分析中的图形**无需通过标签、单位和标题来修饰**；这些图形是探索性的（临时应急用的）。但是，它们应**具有合适的类型，并能有效传递你从中搜集的信息**。
  c. 你可以在相同的 R 区块中迭代图形，但你无需在分析中说明每一次的图形迭代。

#### 2. “最终图形和摘要”结尾部分

  a. 从分析报告中**选择三个图形来进行修饰**，并在这一部分中进行分享。三个图形应该呈现不同的趋势，并且应该由合适的标签、单位和标题来修饰（更多信息，请参见项目评估准则）。

#### 3. 称为“反思”的最终部分

  a. 在该部分中，应通过几句话说明你付出的努力、取得的成功和未来如何探索数据集的想法（更多信息，请参见项目评估准则）。

### （五）第五步 - 拼合 RMD 文件
你拼合的 RMD 文件不应该是一个很长的 R 代码块。
它应包含文本和穿插于其中的图形，目的是使阅读该文件的读者能够深入了解你在探索数据时思考的问题。

### （六）第六步 - 记录数据（如果你选择了自己的数据集）
你提交的数据集（仅当你选择了自己的数据集时）应包含一个文本文件，该文件类似于 R 文档中那些描述数据源的文件；还应包含对数据集中的变量的解释（变量的定义、单位、分类变量的级别，以及数据生成过程，例如在可能时是如何收集数据的）。


## 三、项目模板RMD文件
请下载 项目模板文件，或从下载 EDA 课程教材压缩文件 中找到该模版文件，开始你的分析。

### （一）格式注意事项
我们希望你提交一个可读的 RMD 文件。为了帮助你准备项目，请查看以下注意事项。
  1. 拼合的 HTML 输出应可读。请务必查看你拼合的 HTML 文件，并且检查代码和图形是否正确。
  2. 使用哈希或英镑符号将 RMD 或 R-Markdown 文件中 R 代码的注释包含在 r 代码块中。
  3. 在 RMD 或 R-Markdown 文档中，在 r 代码块外加上 # 符号将创建一个 H1 标题。
  4. 请确认所有图片在导出的 HTML 文件中显示正常。


## 四、评估和提交
### （一）评估
使用项目评估准则检查项目。
如果你对项目感到满意，说明你已准备好提交！
如果你觉得在某个类别上还有改进的空间，那么请继续完善以符合规范！

你的项目会由优达学城项目导师根据相同的项目评估准则进行评估。
为使你通过考核，你提交的项目必须在每一个类别上都“符合规格”。

### （二）提交
准备好提交项目了吗？点击下方的“提交项目”按钮，按照指示进行。
 - 你可以向我们发送文件的 GitHub 链接或者上传压缩目录（压缩文件）。
 - 压缩文件夹应包含**文本文件**，其中列出了网站、书籍、论坛、博客文章和 GitHub 版本库等你在提交的项目中参考或使用的资源（如果你未使用这类资源，请**填写 N/A**）。
 
我们最多需要一周的时间来对项目进行评分，但是多数情况下无需一周。项目评审完毕后，你会收到电子邮件。

如果你在提交项目时遇到问题，或者想查看提交状态，请发送电子邮件至 support@youdaxue.com 联系我们。

### （三）你提交的项目中应包含哪些内容？
1. RMD 文件，包含分析报告（最终图形和摘要以及反思）
2. 使用 knitr 包从 RMD 文件拼合而来的 HTML 文件
3. 原始数据集和数据源——如果你使用了自己的数据，而不是优达学城推荐的数据（注意：如果你使用的是优达学城推荐的数据集，则无需提交原始数据集）
4. 列出以下内容的列表：网站、书籍、论坛、博客文章、GitHub 版本库等你在创建提交的项目时参考或使用的资源（如果你未使用这类资源，请填写 N/A）

## 五、示例项目

最终项目是分析数据集中的变量和关系。你的最终项目应类似于此示例项目。它的结构应该是：一个分析部分，一个最终图形部分和一个反思部分。用于这些部分的模板已在文件的上一个部分提供，你也可以从指导笔记中找到该模板。

至少花 10 分钟时间查看示例项目，以便在启动项目之前了解你将要做哪些事。

## 六、项目提交
使用 R 并应用探索性数据分析技术，从而**研究一个变量与多个变量的关系并探索选定数据集的分布、异常值和反常现象**。

### （一）有关项目提交的常见问题
为帮助你获得成功，我们建议你对照以下常见问题列表来检查你提交的项目。你必须在项目中避免这些常见问题，才能通过考核。

- 数据处理或转换（创建分类变量）应包含在 RMD 文件和最终拼合的 HTML 输出中。
- 未包含反思部分。
- 反思部分不是 RMD 文件中的最后一个部分。
- 未包含最终图形部分。
- 最终图形部分未处于 RMD 文件的结尾（在反思部分之前）。
- 最终图形部分未包含三个图形。
- 最终图形部分中的一个或多个图形未揭示出数据集的结果或模式。
- 最终图形未经修饰，并且缺失标题或单位。
- 为最终图形部分中的数据选择了不合适的图形。

### （二）创建有效的图形
RMD 文件中的最终图形部分应包含**三个经修饰的图形**，使人能深入了解你调查的数据集。

**每个图形还应包含与图形显示的内容有关的说明或描述**。

要确定这三个图形是否有效，请参阅文档创建有效的图形。该文档介绍了项目评估人员过去遇到的四个常见问题，以及改进这些图形的方法。

提醒： 如果你选择上传文档，在上传之前，我们建议将 zip 文件以及其内部文件的文件名改为 英文 ，以尽可能避免上传过程中的问题发生。

## 附：模板中提示的技巧
**隐藏HTML输出中的代码和警告**，可以设置参数为：{r echo=FALSE, message=FALSE, warning=FALSE}

**更改代码显示图的高度和宽度**，可以使用fig.height和fig.width参数

**使用模板**，引导探索

相关矩阵不需要分析所有的变量，同时可考虑使用psych包来绘制相关矩阵（感觉更美观）

**选择合适的调色板并设置绘图主题**，可以使用使用了RColorBrewer包中的sequential调色板;其他变量可能需要qualitative或diverging调色板。注意：有三种类型的颜色方案可供选择：定性（使用带有ColorBrewer相关函数的type =“qual”选项），sequential（type =“seq”）和diverging（type =“div”）。

